### ISSUE TITLE
main.rs does not compile

### ISSUE THREAD

**Issue by fs008** [sivizius/secunet_ti_konnektor_pin_calculator#1]
main.rs does not compile but throws error E0554 for line 1, 2 and 3.

Using an unstable nightly build is not an option.

**Comment by sivizius** [comment]
Try previous commit

**Comment by fs008** [comment]
Thx, previous commit compiles flawless.
What do i have to do with these PINs, in order to decrypt the whole filesystem of secunet konnektor? Why 6 PIN's ? the box has only 3 cardreaders, only 2 Smc's !?
Is there a chance to obtain a more detailed documentation than the c't paper ?

**Comment by sivizius** [comment]
I am the wrong person to ask: I just reverse-engineered a binary and reimplemented it in Rust. This implementation is the how, not the why, sorry. Also: The `src/legacy.rs` is a version that does not need nightly.
